# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tate/CLionProjects/yoda

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tate/CLionProjects/yoda

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tate/CLionProjects/yoda/CMakeFiles /home/tate/CLionProjects/yoda/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tate/CLionProjects/yoda/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yoda

# Build rule for target.
yoda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yoda
.PHONY : yoda

# fast build rule for target.
yoda/fast:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/build
.PHONY : yoda/fast

calc_value.o: calc_value.cpp.o

.PHONY : calc_value.o

# target to build an object file
calc_value.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/calc_value.cpp.o
.PHONY : calc_value.cpp.o

calc_value.i: calc_value.cpp.i

.PHONY : calc_value.i

# target to preprocess a source file
calc_value.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/calc_value.cpp.i
.PHONY : calc_value.cpp.i

calc_value.s: calc_value.cpp.s

.PHONY : calc_value.s

# target to generate assembly for a file
calc_value.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/calc_value.cpp.s
.PHONY : calc_value.cpp.s

core.o: core.cpp.o

.PHONY : core.o

# target to build an object file
core.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/core.cpp.o
.PHONY : core.cpp.o

core.i: core.cpp.i

.PHONY : core.i

# target to preprocess a source file
core.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/core.cpp.i
.PHONY : core.cpp.i

core.s: core.cpp.s

.PHONY : core.s

# target to generate assembly for a file
core.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/core.cpp.s
.PHONY : core.cpp.s

list.o: list.cpp.o

.PHONY : list.o

# target to build an object file
list.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/list.cpp.o
.PHONY : list.cpp.o

list.i: list.cpp.i

.PHONY : list.i

# target to preprocess a source file
list.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/list.cpp.i
.PHONY : list.cpp.i

list.s: list.cpp.s

.PHONY : list.s

# target to generate assembly for a file
list.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/list.cpp.s
.PHONY : list.cpp.s

lolcat_version.o: lolcat_version.cpp.o

.PHONY : lolcat_version.o

# target to build an object file
lolcat_version.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/lolcat_version.cpp.o
.PHONY : lolcat_version.cpp.o

lolcat_version.i: lolcat_version.cpp.i

.PHONY : lolcat_version.i

# target to preprocess a source file
lolcat_version.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/lolcat_version.cpp.i
.PHONY : lolcat_version.cpp.i

lolcat_version.s: lolcat_version.cpp.s

.PHONY : lolcat_version.s

# target to generate assembly for a file
lolcat_version.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/lolcat_version.cpp.s
.PHONY : lolcat_version.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/main.cpp.s
.PHONY : main.cpp.s

process_line.o: process_line.cpp.o

.PHONY : process_line.o

# target to build an object file
process_line.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/process_line.cpp.o
.PHONY : process_line.cpp.o

process_line.i: process_line.cpp.i

.PHONY : process_line.i

# target to preprocess a source file
process_line.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/process_line.cpp.i
.PHONY : process_line.cpp.i

process_line.s: process_line.cpp.s

.PHONY : process_line.s

# target to generate assembly for a file
process_line.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/process_line.cpp.s
.PHONY : process_line.cpp.s

string_stack.o: string_stack.cpp.o

.PHONY : string_stack.o

# target to build an object file
string_stack.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/string_stack.cpp.o
.PHONY : string_stack.cpp.o

string_stack.i: string_stack.cpp.i

.PHONY : string_stack.i

# target to preprocess a source file
string_stack.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/string_stack.cpp.i
.PHONY : string_stack.cpp.i

string_stack.s: string_stack.cpp.s

.PHONY : string_stack.s

# target to generate assembly for a file
string_stack.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/string_stack.cpp.s
.PHONY : string_stack.cpp.s

terminal_colors.o: terminal_colors.cpp.o

.PHONY : terminal_colors.o

# target to build an object file
terminal_colors.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/terminal_colors.cpp.o
.PHONY : terminal_colors.cpp.o

terminal_colors.i: terminal_colors.cpp.i

.PHONY : terminal_colors.i

# target to preprocess a source file
terminal_colors.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/terminal_colors.cpp.i
.PHONY : terminal_colors.cpp.i

terminal_colors.s: terminal_colors.cpp.s

.PHONY : terminal_colors.s

# target to generate assembly for a file
terminal_colors.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/terminal_colors.cpp.s
.PHONY : terminal_colors.cpp.s

termio.o: termio.cpp.o

.PHONY : termio.o

# target to build an object file
termio.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/termio.cpp.o
.PHONY : termio.cpp.o

termio.i: termio.cpp.i

.PHONY : termio.i

# target to preprocess a source file
termio.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/termio.cpp.i
.PHONY : termio.cpp.i

termio.s: termio.cpp.s

.PHONY : termio.s

# target to generate assembly for a file
termio.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/termio.cpp.s
.PHONY : termio.cpp.s

top_modifiers.o: top_modifiers.cpp.o

.PHONY : top_modifiers.o

# target to build an object file
top_modifiers.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/top_modifiers.cpp.o
.PHONY : top_modifiers.cpp.o

top_modifiers.i: top_modifiers.cpp.i

.PHONY : top_modifiers.i

# target to preprocess a source file
top_modifiers.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/top_modifiers.cpp.i
.PHONY : top_modifiers.cpp.i

top_modifiers.s: top_modifiers.cpp.s

.PHONY : top_modifiers.s

# target to generate assembly for a file
top_modifiers.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/top_modifiers.cpp.s
.PHONY : top_modifiers.cpp.s

user_types.o: user_types.cpp.o

.PHONY : user_types.o

# target to build an object file
user_types.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/user_types.cpp.o
.PHONY : user_types.cpp.o

user_types.i: user_types.cpp.i

.PHONY : user_types.i

# target to preprocess a source file
user_types.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/user_types.cpp.i
.PHONY : user_types.cpp.i

user_types.s: user_types.cpp.s

.PHONY : user_types.s

# target to generate assembly for a file
user_types.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/user_types.cpp.s
.PHONY : user_types.cpp.s

user_variables.o: user_variables.cpp.o

.PHONY : user_variables.o

# target to build an object file
user_variables.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/user_variables.cpp.o
.PHONY : user_variables.cpp.o

user_variables.i: user_variables.cpp.i

.PHONY : user_variables.i

# target to preprocess a source file
user_variables.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/user_variables.cpp.i
.PHONY : user_variables.cpp.i

user_variables.s: user_variables.cpp.s

.PHONY : user_variables.s

# target to generate assembly for a file
user_variables.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/user_variables.cpp.s
.PHONY : user_variables.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/utils.cpp.s
.PHONY : utils.cpp.s

win_supp.o: win_supp.cpp.o

.PHONY : win_supp.o

# target to build an object file
win_supp.cpp.o:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/win_supp.cpp.o
.PHONY : win_supp.cpp.o

win_supp.i: win_supp.cpp.i

.PHONY : win_supp.i

# target to preprocess a source file
win_supp.cpp.i:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/win_supp.cpp.i
.PHONY : win_supp.cpp.i

win_supp.s: win_supp.cpp.s

.PHONY : win_supp.s

# target to generate assembly for a file
win_supp.cpp.s:
	$(MAKE) -f CMakeFiles/yoda.dir/build.make CMakeFiles/yoda.dir/win_supp.cpp.s
.PHONY : win_supp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... yoda"
	@echo "... edit_cache"
	@echo "... calc_value.o"
	@echo "... calc_value.i"
	@echo "... calc_value.s"
	@echo "... core.o"
	@echo "... core.i"
	@echo "... core.s"
	@echo "... list.o"
	@echo "... list.i"
	@echo "... list.s"
	@echo "... lolcat_version.o"
	@echo "... lolcat_version.i"
	@echo "... lolcat_version.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... process_line.o"
	@echo "... process_line.i"
	@echo "... process_line.s"
	@echo "... string_stack.o"
	@echo "... string_stack.i"
	@echo "... string_stack.s"
	@echo "... terminal_colors.o"
	@echo "... terminal_colors.i"
	@echo "... terminal_colors.s"
	@echo "... termio.o"
	@echo "... termio.i"
	@echo "... termio.s"
	@echo "... top_modifiers.o"
	@echo "... top_modifiers.i"
	@echo "... top_modifiers.s"
	@echo "... user_types.o"
	@echo "... user_types.i"
	@echo "... user_types.s"
	@echo "... user_variables.o"
	@echo "... user_variables.i"
	@echo "... user_variables.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... win_supp.o"
	@echo "... win_supp.i"
	@echo "... win_supp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

